id: A6188168B
base_file: f2CE0.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:54:40.789610
  last_modified_at: 2022-05-30 22:54:40.789614
