id: A6188168B
base_file: fDD14.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:54:40.792602
  last_modified_at: 2022-05-30 22:54:40.792605
