id: A6188168B
base_file: fBE15.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:54:40.791688
  last_modified_at: 2022-05-30 22:54:40.791690
